alias ls='ls --color=auto'
alias lal='ls -al'
alias ll='ls -l'
alias krmevicted='kubectl get po | grep Evicted| awk '\''{print $1}'\''| xargs -n 1 kubectl delete pod'
alias dfh='df -h -x squashfs -x tmpfs -x devtmpfs'
alias claude='/home/timmy/.local/bin/claude --allow-dangerously-skip-permissions'
alias gemini='node /home/timmy/npm/bin/gemini'
alias copilot='node /home/timmy/npm/bin/copilot'
alias codex='node /home/timmy/npm/bin/codex --dangerously-bypass-approvals-and-sandbox'
alias dev='~/.config/dev.sh'
alias fixclaude='~/.config/guix-home/fix-claude.sh'
