alias ls='ls --color=auto'
alias lal='ls -al'
alias ll='ls -l'
alias krmevicted='kubectl get po | grep Evicted| awk '\''{print $1}'\''| xargs -n 1 kubectl delete pod'
alias dfh='df -h -x squashfs -x tmpfs -x devtmpfs'
alias claude='node /home/timmy/npm/bin/claude --allow-dangerously-skip-permissions'
alias gemini='node /home/timmy/npm/bin/gemini'
alias copilot='node /home/timmy/npm/bin/copilot'
alias dev='~/.config/dev.sh'
