;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
  (list "s6"
        "slurp"
        "grim"
        "ublock-origin-chromium"
        "ungoogled-chromium-wayland"
        "netsurf"
        "gst-plugins-good"
        "gst-plugins-base"
        "pulseaudio"
        "i3status"
        "pavucontrol"
        "rhythmbox"
        "pango"
        "sway"
        "pinentry"
        "password-store"
        "alacritty"
        "icecat"
        "pipewire"
        "dbus"
        "xdg-utils"
        "autoconf"
        "ccls"
        "ripgrep"
        "ntp"
        "ninja"
        "interception-tools"
        "gstreamer"
        "rust"
        "meson"
        "utf8proc"
        "curl"
        "clang-toolchain"
        "cairo"
        "gnupg"
        "isync"
        "go"
        "gcc-toolchain"
        "notmuch"
        "git"
        "emacs-pgtk-native-comp"
        "rsync"
        "ispell"
        "libjpeg"
        "gperf"
        "flex"
        "bison"
        "perl"
        "libsndfile"
        "eudev"
        "alsa-lib"
        "font-wqy-zenhei"
        "alsa-utils"
        "strace"
        "libnsutils"
        "libdom"
        "expat"
        "pkg-config"
        "make"
        "font-gnu-freefont"
        "gs-fonts"
        "fontconfig"
        "font-dejavu"
        "swayidle"
        "zsh"))
